### ISSUE TITLE
Search result not loading

### ISSUE THREAD

**Issue by paulacamargoz** [alexdglover/linkets#10]
Has been more than 2 weeks that I can't link tickets on Zendesk. It shows it's searching for the ticket, but no result is returned. Also, for tickets already linked, I cannot access them on the Linkets container, they don't appear there. 
Is someone working on this bug?

**Comment by alexdglover** [comment]
Sorry to hear you're having an issue. Linkets is built on the Zendesk search API and tickets API. Sometimes linked tickets don't display immediately because the tickets haven't been re-indexed yet within Zendesk's search infrastructure. Sometimes there is an error updating the ticket via the API, but the error isn't displayed in the UI.

As a front-end app, it is difficult to debug issues without being able to "inspect" it when the issue occurs. If you're willing, you can use the 'Console' tab of [Chrome Developer Tools](https://developers.google.com/web/tools/chrome-devtools) to look for the cause of the error. If you can provide me with some more information, I can try to reproduce and fix the issue.

Also, please check the tags set on these tickets - if the tags are set correctly, and there are no errors in the Chrome console, then the issue is with Zendesk search results rather than with the Linkets app.

Please let me know if you can provide more detail on the bug, otherwise will close the issue as stale.
