### ISSUE TITLE
Linkets search not pulling new tickets

### ISSUE THREAD

**Issue by JustinMack** [alexdglover/linkets#11]
Hello,

We use Linkets in Zendesk and we have multiple users that are trying to link tickets in Zendesk and the app is not finding the tickets. The tickets both exist in the system but I cannot  link them together from either ticket because the search function is not pulling them. Another user is also experiencing this error.

Please let me know what we can do.

Thank you,

Justin Mack

**Comment by JustinMack** [comment]
Any update? We're still running into instances where we search for a created ticket but the search doesn't work.

**Comment by alexdglover** [comment]
Sorry to hear you're having an issue. Linkets is built on the Zendesk search API and tickets API. Sometimes linked tickets don't display immediately because the tickets haven't been re-indexed yet within Zendesk's search infrastructure. Sometimes there is an error updating the ticket via the API, but the error isn't displayed in the UI.

As a front-end app, it is difficult to debug issues without being able to "inspect" it when the issue occurs. If you're willing, you can use the 'Console' tab of [Chrome Developer Tools](https://developers.google.com/web/tools/chrome-devtools) to look for the cause of the error. If you can provide me with some more information, I can try to reproduce and fix the issue.

If there are no errors in Chrome's console, it's possible that the issue is with Zendesk search itself or that the tickets have not been indexed by the search infrastructure yet.
