### ISSUE TITLE
Links does not wotk

### ISSUE THREAD

**Issue by AstridGlotin333** [alexdglover/linkets#12]
When I search for a ticket in Linkets, I find it, then link it, but it does not work, does not succeed. The tickets stay with "There are no tickets linked to the current ticket"

What can I do ? 

Thanks 

Astrid

**Comment by alexdglover** [comment]
Sorry to hear you're having an issue. Linkets is built on the Zendesk search API and tickets API. Sometimes linked tickets don't display immediately because the tickets haven't been re-indexed yet within Zendesk's search infrastructure. If you wait a minute and refresh, do the issues appear in the Linkets section of the sidebar?
