### ISSUE TITLE
Tickets are linked by there is no hyperlink in the app sections to redirect from 1 ticket to another 

### ISSUE THREAD

**Issue by KaterynaKlymentenko** [alexdglover/linkets#15]

**Comment by alexdglover** [comment]
Sorry to hear you're having an issue. Linkets is built on the Zendesk search API and tickets API. Sometimes linked tickets don't display immediately because the tickets haven't been re-indexed yet within Zendesk's search infrastructure. If you wait a minute and refresh, are the linked tickets displayed?

**Comment by zenbros** [comment]
The ticket was submitted some time ago - months if I recall correctly.  You
pushed an update and the issue resolved after that time.

From what I could tell based on the timestamp of the last update, when this
occurred, the extension hadn't been updated for several months and simply
broke.  We have again been identifying Linkets as an appropriate solution
for our clients.







T.J. BUMGARDNER
*CEO*
Need to chat?  Click here <https://calendly.com/zenbros> to schedule a
meeting
