### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by cbell2021** [alexdglover/linkets#16]
I had to literally search, select the ticket, select child 2 to 3 times before it would render.  The next day they were completely unlinked.

**Comment by alexdglover** [comment]
Sorry to hear you're having an issue. Linkets is built on the Zendesk search API and tickets API. Sometimes linked tickets don't display immediately because the tickets haven't been re-indexed yet within Zendesk's search infrastructure. Sometimes there is an error updating the ticket via the API, but the error isn't displayed in the UI.

As a front-end app, it is difficult to debug issues without being able to "inspect" it when the issue occurs. If you're willing, you can use the 'Console' tab of [Chrome Developer Tools](https://developers.google.com/web/tools/chrome-devtools) to look for the cause of the error. If you can provide me with some more information, I can try to reproduce and fix the issue.

Without more information, there's not much I can do.
