### ISSUE TITLE
Tickets only linking one way

### ISSUE THREAD

**Issue by FloorFoundHeather** [alexdglover/linkets#22]
**Before you submit**
- [x] I understand Zendesk does not support this app, nor does Zendesk pay for this app
- [x] I understand the author does not get paid to write or support this app, he just tries to provide a useful app

**Describe the bug**
When linking a ticket to another it only shows the link on one ticket, not both. 

**To Reproduce**
1. Go to 'any ticket'
2. Attempt to link to any other ticket
3. Refresh the screen on both tickets

**Expected behavior**
When linking a ticket to another ticket, I expect that the link would show on both tickets. I believe this was the case previously, but noticed that it is no longer doing that

**Screenshots**
Screenshots attached: ![image (9)](https://user-images.githubusercontent.com/104791489/166308807-53508200-d11c-4155-ad59-6b126f359a91.png)
![image (10)](https://user-images.githubusercontent.com/104791489/166308837-237f98c2-2ef8-4288-8f45-e203d7b9b94e.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser - chrome

**Comment by chapaner** [comment]
Hi. Has there been any progress on this one? It would be great if the app linked in both directions so you can see the link in both relevant tickets.

**Comment by markimarc** [comment]
Is in the child ticket the tag present, or not?
![image](https://user-images.githubusercontent.com/6544290/176143985-db6c6839-c3a3-402b-b9a9-5033ea14b34d.png)
The app shows only parent tickets if the tag is present in the ticket.

**Comment by alexdglover** [comment]
hey @FloorFoundHeather , 9 times out of 10 Linkets issues are because one of the two tickets are closed tickets. In order for Linkets to work properly, it writes a tag on both the current ticket, and the ticket you're linking to. @markimarc 's screenshot is an example of the tag that Linkets creates.

As you probably know, closed tickets are no longer editable, including tags on the ticket. If you are trying to link from/to is a closed ticket, it tries to write the tag and fails, leading to issues like this.

So first question - are either of the tickets you're working closed?
