### ISSUE TITLE
Have to search/link twice to link issues in Zendesk

### ISSUE THREAD

**Issue by gdesjardin** [alexdglover/linkets#8]
Every time I attempt to search for and link a previous Zendesk ticket to a current ticket, I have to go through the Search and Link steps twice before the previous ticket actually shows up as linked.

**Comment by alexdglover** [comment]
Sorry to hear you're having an issue. Linkets is built on the Zendesk search API and tickets API. Sometimes linked tickets don't display immediately because the tickets haven't been re-indexed yet within Zendesk's search infrastructure. If this the case, waiting a few seconds and refreshing the page will fix the issue.

Sometimes there is an error updating the ticket via the API, but the error isn't displayed in the UI. As a front-end app, it is difficult to debug issues without being able to "inspect" it when the issue occurs. If you're willing, you can use the 'Console' tab of [Chrome Developer Tools](https://developers.google.com/web/tools/chrome-devtools) to look for the cause of the error. If you can provide me with some more information, I can try to reproduce and fix the issue.

Let me know if waiting and refreshing fixes your issue, or if you find a bug in the console.

**Comment by gdesjardin** [comment]
Hi Alex,

 

Thank you for the follow up.  I ran dev tools while doing this, and attached is the result.  It appears to error both the first time I try to link a related ticket (which is unsuccessful) and the second time (which is successful).  I hadn’t noticed it before, but the same thing happens when I try to unlink a ticket – I have to do it twice for it to take effect.

 

Hopefully this helps.  Let me know if you have any other questions.

 

Thanks!

 

Gail
