### ISSUE TITLE
Issues with opening a linked ticket in new tab

### ISSUE THREAD

**Issue by Fallon1** [alexdglover/linkets#9]
If you click on the link, it opens linked ticket in the same tab. 
However, if you click on it 'open in a new tab' you see a zendesk search 
page instead - see attachment.

<img width="1674" alt="Screenshot 2020-05-25 at 09 42 24" src="https://user-images.githubusercontent.com/62431529/82801488-ac7a0580-9e7d-11ea-973b-4943b395f647.png">

**Comment by Fallon1** [comment]
Do you have any updates regarding the bug?

**Comment by alexdglover** [comment]
Hey @Fallon1 - thanks for the detailed bug and screenshot.

While developing the app, I originally had the links open in a new tab by default. However, since the Zendesk UI implements its own form of tabs within a single browser tab, I decided to stick with the "native" Zendesk look and feel instead. I'll take a look to see if I can support both options, but if not, I will stick with the Zendesk-style tab behavior.

**Comment by Fallon1** [comment]
Hi Alex, 

Thank you for your reply and for the explanation! 

I wish you a nice day, 

Fallon
